
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
execbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-execbeat>>

[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the HTTP url was called. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

The name of the log event. This field is set to the value specified for the `document_type` option in the url section of the Execbeat config file.


==== fields

type: dict

required: False

Contains user configurable fields.


[[exported-fields-execbeat]]
=== Execbeat information fields

Contains information about the command execution.



=== exec fields


==== command

type: string

The command executed by Execbeat.


==== stdout

type: string

Standard output produced by the command executed by Execbeat.


==== stderr

type: string

Standard error produced by the command executed by Execbeat.


